http:
  routers:
    traefik:
      rule: "Host(`traefik.merinal.dz`)"
      service: "api@internal"
      tls:
        domains:
          - main: "merinal.dz"
            sans:
              - "*.merinal.dz"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
